name: financial_risk
version: "1.0.0"
config-version: 2

profile: financial_risk

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  ml_train_end_step: 322
  ml_validation_end_step: 375

models:
  financial_risk:
    staging:
      +materialized: view

    intermediate:
      +materialized: view

    marts:
      +materialized: table

